language: php
php:
- 5.6
addons:
  postgresql: '9.4'
install:
- pecl install PDO_PGSQL
- composer install
env:
  global:
  - APP_ENV=testing
  - DB_CONNECTION=pgsql
  - DATABASE_URL=postgres://postgres:@localhost:5432/call_tracking_test
  - TWILIO_APP_SID=somefak3apps1d
before_script:
- psql -c 'create database call_tracking_test;' -U postgres
- php artisan migrate
